export const materialList = [
  { name: 'Acetal (POM)', density: 1.41 },
  { name: 'Acrylic (PMMA)', density: 1.19 },
  { name: 'Acrylonitrile Butadiene Styrene (ABS)', density: 1.05 },
  { name: 'Aluminum 1100', density: 2.7 },
  { name: 'Aluminum 1100', density: 2.7 },
  { name: 'Aluminum 2017', density: 2.78 },
  { name: 'Aluminum 2024', density: 2.78 },
  { name: 'Aluminum 3003', density: 2.71 },
  { name: 'Aluminum 5052', density: 2.68 },
  { name: 'Aluminum 5083', density: 2.76 },
  { name: 'Aluminum 5754', density: 2.66 },
  { name: 'Aluminum 6060', density: 2.76 },
  { name: 'Aluminum 6061', density: 2.7 },
  { name: 'Aluminum 6082', density: 2.83 },
  { name: 'Aluminum 7075', density: 2.78 },
  { name: 'Aluminum 7075-T651', density: 2.83 },
  { name: 'Beryllium Copper', density: 8.65 },
  { name: 'Brass', density: 8.53 },
  { name: 'Bronze C510', density: 8.7 },
  { name: 'Carbon Fiber Reinforced Polymer (CFRP)', density: 1.5 },
  { name: 'Copper', density: 8.96 },
  { name: 'Delrin', density: 1.41 },
  { name: 'Ertacetal C', density: 1.42 },
  { name: 'Ertacetal H', density: 1.39 },
  { name: 'Ertacetal R', density: 1.35 },
  { name: 'Hastelloy X', density: 8.9 },
  { name: 'Invar', density: 8.0 },
  { name: 'Inconel 625', density: 8.44 },
  { name: 'Inconel 718', density: 8.19 },
  { name: 'Magnesium AZ31B', density: 1.78 },
  { name: 'Molybdenum', density: 10.2 },
  { name: 'Nylon (PA)', density: 1.15 },
  { name: 'Plastic ABS', density: 1.04 },
  { name: 'Plastic PA 6', density: 1.14 },
  { name: 'Plastic PE', density: 0.96 },
  { name: 'Plastic PC', density: 1.2 },
  { name: 'Plastic POM', density: 1.41 },
  { name: 'Plastic PP', density: 0.9 },
  { name: 'Plastic PET', density: 1.38 },
  { name: 'PEEK', density: 1.32 },
  { name: 'Polycarbonate (PC)', density: 1.2 },
  { name: 'Polyethylene (PE)', density: 0.96 },
  { name: 'Polyethylene Terephthalate (PET)', density: 1.38 },
  { name: 'Polypropylene (PP)', density: 0.9 },
  { name: 'Polystyrene (PS)', density: 1.05 },
  { name: 'Polyvinyl Chloride (PVC)', density: 1.4 },
  { name: 'Stainless Steel 201', density: 7.98 },
  { name: 'Stainless Steel 304', density: 8.0 },
  { name: 'Stainless Steel 316', density: 8.0 },
  { name: 'Stainless Steel 410', density: 7.75 },
  { name: 'Stainless Steel 420', density: 7.76 },
  { name: 'Stainless Steel 430', density: 7.7 },
  { name: 'Stainless Steel 439', density: 7.7 },
  { name: 'Stainless Steel 904L', density: 7.85 },
  { name: 'Steel DC01', density: 7.83 },
  { name: 'Steel DC03', density: 7.83 },
  { name: 'Steel DC04', density: 7.83 },
  { name: 'Steel DC05', density: 7.83 },
  { name: 'Steel DC06', density: 7.83 },
  { name: 'Tantalum', density: 16.6 },
  { name: 'Tool Steel P20/1.2311', density: 7.78 },
  { name: 'Titanium Ti-6Al-4V', density: 4.43 },
  { name: 'Tungsten', density: 19.25 },
  { name: 'Tungsten Carbide', density: 15.6 },
  { name: 'Zinc', density: 7.14 }
];
