export const SET_OPEN = 'SET_OPEN';
export const SET_CLOSE = 'SET_CLOSE';
export const SET_MSG = 'SET_MSG';
export const SET_SEVERITY = 'SET_SEVERITY';
export const SET_BOX_QUANTITY = 'SET_BOX_QUANTITY';
export const SET_PRODUCTION_BOX_QUANTITY = 'SET_PRODUCTION_BOX_QUANTITY';
export const SET_NOTIFICATION_QUANTITY = 'SET_NOTIFICATION_QUANTITY';
